[package]
name = "pieskieo-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
bytes.workspace = true
parking_lot.workspace = true
uuid.workspace = true
sqlparser.workspace = true
roaring.workspace = true
rand.workspace = true
bincode.workspace = true
serde_cbor.workspace = true
async-trait.workspace = true
tempfile.workspace = true
rayon.workspace = true
hnsw_rs.workspace = true
regex.workspace = true
chrono.workspace = true
sysinfo = "0.30"

[[test]]
name = "pql_mongo_ops"
path = "tests/pql_mongo_ops.rs"

[[test]]
name = "pql_chemistry"
path = "tests/pql_chemistry.rs"

[[test]]
name = "pql_validation"
path = "tests/pql_validation.rs"

[[test]]
name = "pql_derivatives"
path = "tests/pql_derivatives.rs"

[[test]]
name = "pql_window_agg"
path = "tests/pql_window_agg.rs"

[[test]]
name = "pql_string_pg"
path = "tests/pql_string_pg.rs"

[[test]]
name = "pql_json_ops"
path = "tests/pql_json_ops.rs"

[[test]]
name = "pql_datetime"
path = "tests/pql_datetime.rs"
